import { useMemo, useState } from 'react'
import { Bell, Boxes, Building2, ChevronRight, CircleAlert, ClipboardList, Leaf, PackagePlus, Settings, ShieldCheck, ShoppingBag, TrendingUp } from '@blinkdotnew/mobile-ui'
import { Button, ScrollView, SizableText, Switch, XStack, YStack } from '@blinkdotnew/mobile-ui'
import type { AgroNotificationsRow } from '@/lib/db-types'
import type { AppScreen, Order, Product } from '@/lib/agro'
import { GREEN, GREEN_LIGHT, INK, MUTED, money, shortDate } from '@/lib/agro'
import { PageTitle, Surface } from '@/components/AgroShared'

export function BusinessScreen({ screen, products, orders, notifications, onBack, onNavigate }: {
  screen: AppScreen; products: Product[]; orders: Order[]; notifications: AgroNotificationsRow[]; onBack: () => void; onNavigate: (screen: AppScreen) => void
}) {
  const [notificationsOn, setNotificationsOn] = useState(true)
  const [darkMode, setDarkMode] = useState(false)
  const revenue = orders.reduce((sum, order) => sum + Number(order.totalFc), 0)
  const weeklySales = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const date = new Date()
    date.setDate(date.getDate() - (6 - index))
    const total = orders.filter(order => new Date(order.createdAt).toDateString() === date.toDateString()).reduce((sum, order) => sum + Number(order.totalFc), 0)
    return { label: date.toLocaleDateString('fr-FR', { weekday: 'short' }), total }
  }), [orders])
  const chartMax = Math.max(1, ...weeklySales.map(day => day.total))
  const title: Record<string, string> = { admin: 'Espace gestion', inventory: 'Stocks', sales: 'Ventes & statistiques', notifications: 'Notifications', settings: 'Paramètres', about: 'À propos de MKN' }
  return <ScrollView backgroundColor="#F5F7F2" contentContainerStyle={{ padding: 18, paddingBottom: 30 }}>
    <PageTitle title={title[screen] || 'Espace gestion'} subtitle="Kolwezi · Lubumbashi" onBack={onBack} />
    <YStack backgroundColor="#FFF7DC" borderWidth={1} borderColor="#F1E5B9" borderRadius="$4" padding="$3" marginBottom="$3" gap="$1">
      <XStack alignItems="center" gap="$2"><CircleAlert size={17} color="#806411" /><SizableText color="#69540A" size="$3" fontWeight="800">Aperçu gestion — accès restreint</SizableText></XStack>
      <SizableText color="#69540A" size="$2">Les changements partagés au catalogue et aux commandes de tous les clients nécessitent un rôle administrateur sécurisé côté serveur. Cette vue n’affiche que le catalogue public et les commandes de ce compte.</SizableText>
    </YStack>
    {screen === 'admin' && <YStack gap="$3">
      <XStack flexWrap="wrap" gap="$2">
        <MetricCard label="Produits au catalogue" value={String(products.length)} icon={<ShoppingBag size={19} color={GREEN} />} />
        <MetricCard label="Unités en stock" value={String(products.reduce((s, p) => s + Number(p.stock), 0))} icon={<Boxes size={19} color={GREEN} />} />
        <MetricCard label="Commandes de ce compte" value={String(orders.length)} icon={<ClipboardList size={19} color={GREEN} />} />
        <MetricCard label="Total de ces commandes" value={money(revenue)} icon={<TrendingUp size={19} color={GREEN} />} />
      </XStack>
      <SizableText color={INK} size="$5" fontWeight="800" marginTop="$2">Raccourcis</SizableText>
      <XStack flexWrap="wrap" gap="$2">
        <Shortcut title="Gérer le catalogue" icon={<ShoppingBag size={18} color={GREEN} />} onPress={() => onNavigate('inventory')} />
        <Shortcut title="Consulter les stocks" icon={<Boxes size={18} color={GREEN} />} onPress={() => onNavigate('inventory')} />
        <Shortcut title="Commandes" icon={<ClipboardList size={18} color={GREEN} />} onPress={() => onNavigate('sales')} />
        <Shortcut title="Ventes" icon={<TrendingUp size={18} color={GREEN} />} onPress={() => onNavigate('sales')} />
        <Shortcut title="Notifications" icon={<Bell size={18} color={GREEN} />} onPress={() => onNavigate('notifications')} />
        <Shortcut title="Paramètres" icon={<Settings size={18} color={GREEN} />} onPress={() => onNavigate('settings')} />
      </XStack>
      <Surface><YStack gap="$2"><SizableText color={INK} size="$5" fontWeight="800">Commandes récentes</SizableText>{orders.length ? orders.slice(0, 4).map(o => <XStack key={o.id} justifyContent="space-between" paddingVertical="$2" borderTopWidth={1} borderColor="#EEF1EC"><YStack><SizableText color={INK} size="$3" fontWeight="700">{o.id}</SizableText><SizableText color={MUTED} size="$2">{o.city} · {o.status}</SizableText></YStack><SizableText color={GREEN} fontWeight="800">{money(o.totalFc)}</SizableText></XStack>) : <SizableText color={MUTED} size="$3">Aucune commande sur ce compte pour le moment.</SizableText>}</YStack></Surface>
    </YStack>}
    {screen === 'inventory' && <YStack gap="$3">
      <Surface><YStack gap="$3"><XStack justifyContent="space-between" alignItems="center"><SizableText color={INK} size="$5" fontWeight="800">Catalogue et stocks</SizableText><Button disabled backgroundColor={GREEN_LIGHT} color={GREEN} borderRadius="$4" icon={<PackagePlus size={16} color={GREEN} />}>Ajouter</Button></XStack><SizableText color={MUTED} size="$2">Affichage en lecture seule. Le seuil indicatif d’alerte est fixé à 8 unités.</SizableText>{products.map(p => <XStack key={p.id} alignItems="center" justifyContent="space-between" paddingVertical="$2" borderTopWidth={1} borderColor="#EEF1EC"><YStack flex={1}><SizableText color={INK} size="$3" fontWeight="700">{p.name}</SizableText><SizableText color={MUTED} size="$2">{p.category} · {money(p.priceFc)}</SizableText></YStack><YStack backgroundColor={Number(p.stock) < 8 ? '#FFF0E8' : GREEN_LIGHT} paddingHorizontal="$3" paddingVertical="$2" borderRadius="$4"><SizableText color={Number(p.stock) < 8 ? '#A44A28' : GREEN} size="$3" fontWeight="800">{p.stock} unités</SizableText></YStack></XStack>)}</YStack></Surface>
    </YStack>}
    {screen === 'sales' && <YStack gap="$3"><Surface><YStack gap="$3"><SizableText color={INK} size="$5" fontWeight="800">Indicateurs des commandes de ce compte</SizableText><MetricLine label="Nombre de commandes" value={String(orders.length)} /><MetricLine label="Montant cumulé" value={money(revenue)} /><MetricLine label="Ventes cette semaine" value={money(orders.filter(o => Date.now() - new Date(o.createdAt).getTime() < 7 * 86400000).reduce((s,o) => s + Number(o.totalFc), 0))} /></YStack></Surface><Surface><YStack gap="$3"><SizableText color={INK} size="$5" fontWeight="800">Évolution sur 7 jours</SizableText><XStack height={118} alignItems="flex-end" justifyContent="space-between" gap="$2">{weeklySales.map(day => <YStack key={day.label} flex={1} alignItems="center" justifyContent="flex-end" gap="$1"><YStack width="100%" maxWidth={38} height={Math.max(day.total ? 16 : 6, (day.total / chartMax) * 78)} borderTopLeftRadius="$3" borderTopRightRadius="$3" backgroundColor={day.total ? GREEN : '#DCE6DB'} /><SizableText color={MUTED} size="$1">{day.label}</SizableText></YStack>)}</XStack><SizableText color={MUTED} size="$2">Chiffres calculés uniquement à partir des commandes de ce compte.</SizableText></YStack></Surface><Surface><SizableText color={INK} size="$5" fontWeight="800">Commandes récentes</SizableText>{orders.length ? orders.map(o => <XStack key={o.id} justifyContent="space-between" paddingVertical="$3" borderTopWidth={1} borderColor="#EEF1EC"><YStack><SizableText color={INK} size="$3" fontWeight="700">{o.id} · {o.city}</SizableText><SizableText color={MUTED} size="$2">{shortDate(o.createdAt)} · {o.status}</SizableText></YStack><SizableText color={GREEN} fontWeight="800">{money(o.totalFc)}</SizableText></XStack>) : <SizableText color={MUTED} size="$3" marginTop="$2">Les commandes seront visibles ici.</SizableText>}</Surface></YStack>}
    {screen === 'notifications' && <Surface><YStack gap="$2"><SizableText color={INK} size="$5" fontWeight="800">Vos notifications</SizableText>{notifications.length ? notifications.map(item => <XStack key={item.id} alignItems="flex-start" gap="$3" paddingVertical="$3" borderTopWidth={1} borderColor="#EEF1EC"><Bell size={18} color={GREEN} /><YStack flex={1}><SizableText color={INK} size="$3" fontWeight="700">{item.title}</SizableText><SizableText color={MUTED} size="$2">{item.message}</SizableText><SizableText color={MUTED} size="$1">{shortDate(item.createdAt)}</SizableText></YStack></XStack>) : <YStack alignItems="center" gap="$3" padding="$4"><Bell size={34} color={GREEN} /><SizableText color={INK} size="$5" fontWeight="800">Vous êtes à jour</SizableText><SizableText color={MUTED} size="$3" textAlign="center">Les alertes de vos commandes apparaîtront ici.</SizableText></YStack>}</YStack></Surface>}
    {screen === 'settings' && <YStack gap="$3"><Surface><YStack gap="$4"><SizableText color={INK} size="$5" fontWeight="800">Préférences</SizableText><SettingRow title="Notifications" subtitle="Alertes de commande et de livraison" value={notificationsOn} onValue={setNotificationsOn} /><SettingRow title="Mode sombre" subtitle="Apparence de l’application" value={darkMode} onValue={setDarkMode} /></YStack></Surface><Surface><YStack gap="$2"><SizableText color={INK} size="$5" fontWeight="800">Entreprise</SizableText><MetricLine label="Nom" value="MKN Agro Business" /><MetricLine label="Villes desservies" value="Kolwezi, Lubumbashi" /><MetricLine label="Langue" value="Français" /></YStack></Surface><Button chromeless onPress={() => {}}><SizableText color={GREEN} size="$3">Conditions d’utilisation · Confidentialité</SizableText></Button></YStack>}
    {screen === 'about' && <YStack gap="$3"><Surface><YStack alignItems="center" gap="$3" padding="$4"><YStack width={70} height={70} borderRadius="$6" backgroundColor={GREEN} alignItems="center" justifyContent="center"><Leaf size={35} color="#FFFFFF" /></YStack><SizableText color={GREEN} size="$7" fontWeight="800">MKN Agro Business</SizableText><SizableText color={MUTED} size="$4" textAlign="center">Élever aujourd’hui, nourrir demain</SizableText><SizableText color={INK} size="$4" fontWeight="700" textAlign="center">Ensemble pour une agriculture durable</SizableText></YStack></Surface><XStack gap="$2">{['Élevage', 'Agriculture', 'Qualité', 'Confiance'].map(item => <YStack key={item} flex={1} backgroundColor={GREEN_LIGHT} padding="$2" borderRadius="$4" alignItems="center"><SizableText color={GREEN} size="$2" fontWeight="700">{item}</SizableText></YStack>)}</XStack><Surface><YStack gap="$2"><MetricLine label="Kolwezi" value="Service local" /><MetricLine label="Lubumbashi" value="Service local" /></YStack></Surface></YStack>}
  </ScrollView>
}

function MetricCard({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <YStack width="48%" minHeight={112} backgroundColor="#FFFFFF" borderWidth={1} borderColor="#E8ECE5" borderRadius="$5" padding="$3" justifyContent="space-between"><XStack justifyContent="space-between"><SizableText color={MUTED} size="$2">{label}</SizableText>{icon}</XStack><SizableText color={INK} size="$6" fontWeight="800">{value}</SizableText></YStack> }
function Shortcut({ title, icon, onPress }: { title: string; icon: React.ReactNode; onPress: () => void }) { return <Button onPress={onPress} width="48%" height={54} justifyContent="flex-start" backgroundColor="#FFFFFF" borderColor="#E8ECE5" borderWidth={1} borderRadius="$4"><XStack flex={1} alignItems="center" gap="$2">{icon}<SizableText flex={1} color={INK} size="$2" fontWeight="700">{title}</SizableText><ChevronRight size={14} color={MUTED} /></XStack></Button> }
function MetricLine({ label, value }: { label: string; value: string }) { return <XStack justifyContent="space-between" gap="$3" paddingVertical="$2" borderBottomWidth={1} borderColor="#EEF1EC"><SizableText color={MUTED} size="$3">{label}</SizableText><SizableText color={INK} size="$3" fontWeight="700" textAlign="right">{value}</SizableText></XStack> }
function SettingRow({ title, subtitle, value, onValue }: { title: string; subtitle: string; value: boolean; onValue: (v: boolean) => void }) { return <XStack alignItems="center" justifyContent="space-between"><YStack flex={1}><SizableText color={INK} size="$3" fontWeight="700">{title}</SizableText><SizableText color={MUTED} size="$2">{subtitle}</SizableText></YStack><Switch checked={value} onCheckedChange={onValue}><Switch.Thumb /></Switch></XStack> }
